### ISSUE TITLE
relation data undefined

### ISSUE THREAD

**Issue by ngomanhhung** [Wakanda/bower-angular-wakanda#8]
Hi,
I'm using angular-wakanda 0.4.2
Please look at this case:

WakandaDB model:
1-people -> n-appointments -> 1-visit

app:
appointments.$find(params);

result:
people is a deferred object
visit is undefined.

![screen shot 2015-02-06 at 10 02 38 am](https://cloud.githubusercontent.com/assets/5791917/6073351/27ba60aa-ade8-11e4-98b7-e232ed839805.png)

Shouldn't visit be a deferred object as well?

**Comment by ngomanhhung** [comment]
Okay. My bad,
I thought it will always return a deferred object but it's not.
Visit is only returned as deferred object if there's entity linked to appointment.

**Comment by AMorgaut** [comment]
This behavior may be changed a little bit in a future release
In fact you may expect an empty collection which would make your code easier (a forEach on an empty array would not throw an error)

I'll look at it
